<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <ItemGroup>
    <None Include="FVP\Fvp\Fvp.sln" />
    <None Include="FVP\Fvp\Fvp\Fvp.csproj" />
    <None Include="FVP\Fvp\.vs\Fvp\xs\UserPrefs.xml" />
    <None Include="FVP\Fvp\.vs\Fvp\xs\project-cache\Fvp-Debug.json" />
  </ItemGroup>
</Project>
